name: mmoMoney
main: mmo.Money.MMOMoney
version: 1.2
website: TO BE SET
author: Xaymar <MichaelDirks@levelnull.de>
softdepend: [Spout]
description: Utility functions for mmo-minecraft
commands:
permissions:
