name: mmoMoney
version: ${releaseVersion}.${buildNumber}
description: An economy plugin for the mmoMinecraft suite.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Money.MMOMoney
depend: [Spout, mmoCore]

commands:
    money:
        description: 
        aliases: [cash, econ]

permissions:
    mmo.money.*:
        default: false
        children:
            mmo.money.account: true
            mmo.money.get: true
            mmo.money.get.own: true
            mmo.money.get.other: true
            mmo.money.set: true
            mmo.money.set.own: true
            mmo.money.set.other: true
            mmo.money.take: true
            mmo.money.give: true
            mmo.money.drop: true
            mmo.money.admin: true
            mmo.money.admin.account: true
            mmo.money.admin.account.list: true
            mmo.money.admin.account.create: true
            mmo.money.admin.account.reset: true
            mmo.money.admin.account.remove: true
            mmo.money.admin.database: true
            mmo.money.admin.database.purge: true
            mmo.money.admin.database.empty: true
            mmo.money.admin.database.refresh: true
    mmo.money.get.*:
        default: false
        children:
            mmo.money.get.own: true
            mmo.money.get.other: true
    mmo.money.set.*:
        default: false
        children:
            mmo.money.set.own: true
            mmo.money.set.other: true
    mmo.money.admin.*:
        default: false
        children:
            mmo.money.admin: true
            mmo.money.admin.account: true
            mmo.money.admin.account.list: true
            mmo.money.admin.account.create: true
            mmo.money.admin.account.reset: true
            mmo.money.admin.account.remove: true
            mmo.money.admin.database: true
            mmo.money.admin.database.purge: true
            mmo.money.admin.database.empty: true
            mmo.money.admin.database.refresh: true
    mmo.money.admin.account.*:
        default: false
        children:
            mmo.money.admin.account: true
            mmo.money.admin.account.list: true
            mmo.money.admin.account.create: true
            mmo.money.admin.account.reset: true
            mmo.money.admin.account.remove: true
    mmo.money.admin.database.*:
        default: false
        children:
            mmo.money.admin.database: true
            mmo.money.admin.database.purge: true
            mmo.money.admin.database.empty: true
            mmo.money.admin.database.refresh: true
    mmo.money.rightsset.user:
        default: false
        children:
            mmo.money.account: true
            mmo.money.get.own: true
            mmo.money.give: true
            mmo.money.drop: true
    mmo.money.rightsset.mod:
        default: false
        children:
            mmo.money.account: true
            mmo.money.get.own: true
            mmo.money.get.other: true
            mmo.money.set.own: true
            mmo.money.give: true
            mmo.money.take: true
            mmo.money.drop: true
            mmo.money.admin: true
            mmo.money.admin.account: true
            mmo.money.admin.account.list: true
            mmo.money.admin.account.reset: true
            mmo.money.admin.database: true
            mmo.money.admin.database.purge: true
            mmo.money.admin.database.refresh: true
    mmo.money.rightsset.admin:
        default: false
        children:
            mmo.money.account: true
            mmo.money.get.own: true
            mmo.money.get.other: true
            mmo.money.set.own: true
            mmo.money.set.other: true
            mmo.money.give: true
            mmo.money.take: true
            mmo.money.drop: true
            mmo.money.admin: true
            mmo.money.admin.account: true
            mmo.money.admin.account.list: true
            mmo.money.admin.account.create: true
            mmo.money.admin.account.reset: true
            mmo.money.admin.account.remove: true
            mmo.money.admin.database: true
            mmo.money.admin.database.empty: true
            mmo.money.admin.database.purge: true
            mmo.money.admin.database.refresh: true
    mmo.money.account:
        description: "Allow the player to have an Account(necessary for 'take' 'give' 'drop';ignored by 'account create')"
        default: true
    mmo.money.get.own:
        description: "Allow the player to see the content of his moneybag"
        default: true
    mmo.money.get.other:
        description: "Allow the player to see the content of someones moneybag (includes own)"
        default: op
        children:
            mmo.money.get.own: true
    mmo.money.set.own:
        description: "Allow the player to magically make content appear in his moneybag"
        default: op
    mmo.money.set.other:
        description: "Allow the player to magically make content appear in someones moneybag (Includes own)"
        default: op
        children:
            mmo.money.set.own: true
    mmo.money.take:
        description: "Allow the player to take the content from someones moneybag"
        default: op
    mmo.money.give:
        description: "Allow the player to give content from his moneybag to someone"
        default: true
    mmo.money.drop:
        description: "Allow the player to drop content from his moneybag"
        default: true
    mmo.money.admin:
        description: "Allow the player to use the admin commandset"
        default: op
    mmo.money.admin.account:
        description: "Allow the player to use the account commandset"
        default: op
    mmo.money.admin.account.list:
        description: "Allow the player to list all accounts ever created"
        default: op
    mmo.money.admin.account.create:
        description: "Allow the player to create new accounts(not usually needed)"
        default: op
    mmo.money.admin.account.reset:
        description: "Allow the player to reset accounts(resets them to default)"
        default: op
    mmo.money.admin.account.remove:
        description: "Allow the player to remove accounts(not usually needed)"
        default: op
    mmo.money.admin.database:
        description: "Allow the player to use the database commandset"
        default: op
    mmo.money.admin.database.purge:
        description: "Allow the player to purge accounts(unused for 30 days, still at default. DON'T DO THIS WHILE PLAYERS ARE ONLINE)"
        default: op
    mmo.money.admin.database.empty:
        description: "Allow the player to empty the database completely(Removes all accounts and Transactions. HIGHLY DISADVISED TO EVER GRANT ANYONE TO DO THIS)"
        default: false
    mmo.money.admin.database.refresh:
        description: "Allow the player to refresh the database(Writes current changes and reloads all accounts from database, safe to give anyone who wants)"
        default: op
