name: mmoMoney
main: mmo.Money.MMOMoney
version: 0.1
website: TO BE SET
author: Xaymar <MichaelDirks@levelnull.de>
depend: [mmoCore]

description: mmoMoney

commands:
  money:
    description: 
    aliases: [cash,econ]

pemissions:
  mmomoney.*:
    description: Grants all rights that mmoMoney has avaible.
    default: op
    children:
      mmomoney.get: true
      mmomoney.set: true
      mmomoney.take: true
      mmomoney.give: true
      mmomoney.account: true
  mmomoney.account:
    description: Grants the right to have an account.
    default: true
  mmomoney.get:
    description: Grants the right to get the amount of money of someone or yourself
    default: op
    children:
      mmomoney.get.own: true
      mmomoney.get.other: true
  mmomoney.set:
    description: Grants the right to set the amount of money of someone or yourself
    default: op
    children:
      mmomoney.set.own: true
      mmomoney.set.other: true
  mmomoney.get.own:
    description: Grants the right to get the amount of money you have.
    default: op
    children:
      mmomoney.account: true
  mmomoney.get.other:
    description: Grants the right to get the amount of money someone has.
    default: op
  mmomoney.set.own:
    description: Grants the right to set the amount of money you have.
    default: op
    children:
      mmomoney.account: true
  mmomoney.set.other:
    description: Grants the right to set the amount of money someone has.
    default: op
  mmomoney.take:
    description: Grants the right to take money from someone
    default: op
    children:
      mmomoney.account: true
  mmomoney.give:
    description: Grants the right to give money to someone
    default: op
    children:
      mmomoney.account: true
  mmomoney.admin:
    description: Grants access to /money admin
    default: op
  mmomoney.admin.account:
    description: Grants access to account commands
    default: op
  mmomoney.admin.account.*:
    description: Grants all account rights
    default: op
    children:
      mmomoney.admin.account.list: true
      mmomoney.admin.account.create: true
      mmomoney.admin.account.reset: true
      mmomoney.admin.account.remove: true
  mmomoney.admin.account.list:
    description: Grants the right to list accounts and their Data.
    default: op
  mmomoney.admin.account.create:
    description: Grants the right to create new accounts.
    default: op
  mmomoney.admin.account.reset:
    description: Grants the right to reset accounts to the default.
    default: op
  mmomoney.admin.account.remove:
    description: Grants the right to remove accounts.
    default: op
  mmomoney.admin.database:
    description: Grants access to database commands
    default: op
  mmomoney.admin.database.*:
    description: Grants all database rights
    default: op
    children:
      mmomoney.admin.database.purge: true
      mmomoney.admin.database.empty: true
      mmomoney.admin.database.refresh: true
  mmomoney.admin.database.purge:
    description: Grants the right to purge the database of default and unused accounts.
    default: op
  mmomoney.admin.database.empty:
    description: Grants the right to empty the database. Can have horrible effects on plugins using the account system of this.
    default: op
  mmomoney.admin.database.refresh:
    description: Grants the right to refresh the database. Unsaved changes will get lost.
    default: op