name: mmoMoney
main: mmo.Money.MMOMoney
version: 0.1
website: TO BE SET
author: Xaymar <MichaelDirks@levelnull.de>
depend: [mmoCore]

description: mmoMoney

commands:
  money:
    description: 
    aliases: [con,coin,pouch,cash]
    usage: /money 